"""empty message

Revision ID: 7de45267dd95
Revises: 3e8686f4c64e
Create Date: 2020-10-31 11:00:08.329419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de45267dd95'
down_revision = '3e8686f4c64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publish_year', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publish_year')
    # ### end Alembic commands ###
